#!/usr/bin/env bash

set -e

[ / = "${0::1}" ] || exec "$0" "$@"

self=${0##*/}
alias=$(readlink "${0%$self}".alias)
active=$(gcloud config configurations list --filter is_active=true --format 'value(name)')
# safety valve: script path MUST include a component matching the relevant GCP configuration
[[ "$active" = $alias ]] || {
    echo GCP configuration \'$active\' does not match project alias \'$alias\'.
    exit 1
}

PROJECT=$(gcloud config get-value project)

autoscaler_sa=ray-autoscaler-sa-v1
reader_sa=ray-registry-reader-sa
reader_display_name="Ray registry reader service account"

bail() {
    echo "$@"
    exit 1
}

sa_exists() {
    email=$sa@$PROJECT.iam.gserviceaccount.com

    sa_=$(gcloud iam service-accounts list --format 'value(name)' --filter $sa)
    echo [$sa :: $sa_]
    [ "${sa_##*/}" = $email ]
}

create_sa() {
    gcloud iam service-accounts create $sa --display-name "$1"
}

delete_sa() {
    gcloud iam service-accounts delete $email
}

role() {
    gcloud projects $1-iam-policy-binding $PROJECT \
        --member serviceAccount:$email --role $2
}

roles() {
    gcloud projects get-iam-policy $PROJECT \
        --flatten bindings \
        --filter bindings.members~$email \
        --format 'value(bindings.role)'
}

for sa in $autoscaler_sa $reader_sa
do
    case $1 in
        +)
            sa_exists ||
                if [ $sa = $autoscaler_sa ]
                then bail No matching service account [$sa:: $sa_]
                else create_sa "$reader_display_name"
                fi

            role add roles/artifactregistry.reader
            ! [ $sa = $autoscaler_sa ] || role add roles/iam.serviceAccountUser
            ;;
        -)
            ! sa_exists || {
                for role in $(roles)
                do role remove $role
                done
                delete_sa
            }
            ;;
        =)
            ;;
        *)
            bail Usage: $self [=\|+\|-]
    esac
    sa_exists || :
done
