attacker: pathplanner
false_positive: 0.1
false_negative: 0.1
save_graphs: false
save_logs: false
seed: 0
attack_start_time: 0 # average of exponential dist.
reward_mode: downtime-penalty
graph_config: {
  ttc: {easy: 1.0, hard: 10.0, default: 0.0},
  rewards: {high_flag: 100.0, medium_flag: 10.0, low_flag: 1.0, default: 0.0, defense_default: 10.0},
  filename: graphs/2keys1door.yaml,
  root: "attacker:8:enter:8",
}