attacker: pathplanner

save_graphs: false
save_logs: false
seed: 0
reward_mode: uptime-reward

sim_config:
  seed: 0
  attack_start_time: 0 # average of exponential dist.
  false_positive_rate: 0.0
  false_negative_rate: 0.0

graph_config:
  ttc:
    easy: 1.0
    hard: 10.0
    default: 0.0
  rewards:
    high_flag: 100.0
    low_flag: 1.0
    default: 0.0
  filename: graphs/test_graph.yaml
