attacker: random
false_positive: 0.0
save_graphs: false
save_logs: false
false_negative: 0.0
seed: 0
attack_start_time: 0 # average of exponential dist.
reward_mode: simple
graph_config: {
  easy_ttc: 1,
  hard_ttc: 10,
  high_flag_reward: 100,
  medium_flag_reward: 10,
  low_flag_reward: 1,
  filename: graphs/test_graph.yaml, # TODO the format of this filename can be debated
  root: "a.attack",
  seed: 0
}