version: 1
formatters:

  simple:
    format: '[%(levelname)s] - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    #formatter: simple
    filename: trainer.log
    mode: w

  file2:
    class: logging.FileHandler
    #formatter: simple
    filename: simulator.log
    mode: w

root:
  level: DEBUG
  trainer:
    handlers: [file]

  simulator:
    handlers: [file2]

disable_existing_loggers: false