#!/usr/bin/env bash

usage() {
    echo Usage: ${0##*/} CSV1 CSV2
}

normalize() {
    cut -d, -f2- "$1" | sed 's/\.0$//' | sort
}

[ -r "$1" ] || usage
[ -r "$2" ] || usage

colordiff -u <(normalize "$1") <(normalize "$2") | less -R
